name: check-in-proyecto-a
services:
  springboot-app:
  build:
  context: .
  dockerfile: Dockerfile
  ports:
    - "8025:8004" #puerto correspondiente
  networks:
    - my_bridge_network
networks:
  my_bridge_network:
  external: true


